kind: pipeline
name: default

platform:
  arch: amd64

steps:   
  - name: continuous
    pull: if-not-exists
    image: microsoft/dotnet:sdk
    commands:
      - dotnet restore
      - dotnet build --configuration Debug Laren.E2ETests.csproj
      - dotnet test Laren.E2ETests.csproj --no-build --configuration Debug
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
    when:
      branch:
        exclude:
          - develop
          - qa