kind: pipeline

platform:
  arch: amd64

steps:
  - name: build
    environment:
      CAKE_VERSION: "0.30.0"
    when:
      branch:
        include:
          - develop
          - master
          - qa
          
  - name: continuous
    image: microsoft/dotnet:sdk
    commands:
      - dotnet restore
      - dotnet build --configuration Debug Laren.E2ETests.csproj
      - dotnet test Laren.E2ETests.csproj --no-build --configuration Debug
    environment:
      CAKE_VERSION: "0.30.0"
    when:
      branch:
        exclude:
          - develop
          - master
          - qa